runtime: nodejs18

handlers:
# Serve static files from dist directory
- url: /assets
  static_dir: dist/assets
  secure: always

# Serve the main HTML file
- url: /
  static_files: dist/index.html
  upload: dist/index.html
  secure: always

# Catch-all handler for SPA routing
- url: /.*
  static_files: dist/index.html
  upload: dist/index.html
  secure: always

# Enable compression
automatic_scaling:
  min_instances: 0
  max_instances: 10

# Environment variables (if needed)
env_variables:
  NODE_ENV: production